version: '3'


services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.example
    ports:
      - "80:80"
    environment:
      - CONTAINER_ROLE=app

  queue:
    build:
      context: .
      dockerfile: Dockerfile.example
    environment:
      - CONTAINER_ROLE=queue

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile.example
    environment:
      - CONTAINER_ROLE=scheduler