services:
  all:
    build:
      context: .
      dockerfile: Dockerfile.example
    ports:
      - "80:80"
    environment:
      - CONTAINER_ROLE=web,queue,scheduler

  web:
    build:
      context: .
      dockerfile: Dockerfile.example
    ports:
      - "80:80"
    environment:
      - CONTAINER_ROLE=web

  queue:
    build:
      context: .
      dockerfile: Dockerfile.example
    environment:
      - CONTAINER_ROLE=queue

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile.example
    environment:
      - CONTAINER_ROLE=scheduler
