#!/bin/sh -e

export OPTIMIZE_BY_DEFAULT=false
if [ "${APP_ENV}" = "production" ] ; then
    export OPTIMIZE_BY_DEFAULT=true
fi
export OPTIMIZE_CONFIG=${OPTIMIZE_CONFIG:-${OPTIMIZE_BY_DEFAULT}}
export OPTIMIZE_EVENTS=${OPTIMIZE_EVENTS:-${OPTIMIZE_BY_DEFAULT}}
export OPTIMIZE_ROUTES=${OPTIMIZE_ROUTES:-${OPTIMIZE_BY_DEFAULT}}
export OPTIMIZE_VIEWS=${OPTIMIZE_VIEWS:-${OPTIMIZE_BY_DEFAULT}}
